### PR TITLE
Filter out Genres from Discover

### PR DESCRIPTION
**Pull request by Ashton-Sidhu**
Hi @tidusjar - opening up this PR now for discussion + feedback.

This is the PR to introduce filtering out genres from the Discover lists.

TheMovieDB API only has the capability to get a list of all genre mappings and unfortunately does not have a lookup api

### CODE REVIEW

**Comment by Ashton-Sidhu** [comment]
I've added the back end API calls to get the genres and communicate them with the front end.

For the UI, since there are only ~15 or so genres I'm thinking of making the Genre exclusion a drop down instead of a text box, let me know your thoughts!

**Comment by tidusjar** [comment]
Wow that was quick! I'll get onto reviewing asap

**Comment by tidusjar** [comment]
Also I'm fine with making it a drop-down, better for accessibility with such a small set of data

**Comment by Ashton-Sidhu** [comment]
Ok thanks, I'll turn it into a drop down - the component init code will change slightly then as well. Will work on it and push the changes soon.

**Comment by tidusjar** [comment]
Code looks good! I'll do some testing!

**Comment by tidusjar** [comment]
Nice work! All functioning correctly! Thanks a lot for this!

**Pull request merged**
