### PR TITLE
Fix subscribe button for movies

### PR DESCRIPTION
**Pull request by sephrat**
- Deprecate 'subscribed' field from search service which could be incorrect because of caching
- Fixes 'subscribed' field from request service
- Fixes 'Subscribe' button not being displayed for non-4K setups
- Allows admins to subscribe too

### CODE REVIEW

**Comment by tidusjar** [comment]
Now we have moved it, does the UI need to now set the properties from the request rather than the search object?

**Comment by sephrat** [comment]
> Now we have moved it, does the UI need to now set the properties from the request rather than the search object?

It's been done here: https://github.com/Ombi-app/Ombi/commit/dd7219ebf9c2ca31acb89f034d0ae86b2c2d6894
Or did you mean something else?

**Comment by tidusjar** [comment]
I missed that. That does make sense. My only issue is that if anyone is depending on that field in the api it’s not going to work. An example of this would be the mobile app. I suggest we put the v1 back for a bit and then later remove it. That way we can stage the rollout.

**Comment by sephrat** [comment]
Sounds reasonable. Done.

**Pull request merged**
