### PR TITLE
Added possibility for custom favicons

### PR DESCRIPTION
**Pull request by maartenheebink**
As requested in https://features.ombi.io/suggestions/145095/custom-favicon-option

### CODE REVIEW

**Comment by maartenheebink** [comment]
@tidusjar i need approval for starting workflows, could you check if this can be started?

**Comment by maartenheebink** [comment]
also, im sorry, i just noticed that my IDE screwed with the component html (indentation)

**Comment by tidusjar** [comment]
Yeah looks good, do you mind fixing the indentation for that file?

**Comment by maartenheebink** [comment]
Done

**Comment by tidusjar** [comment]
Nice work! Thanks :)

**Pull request merged**
