### PR TITLE
First step towards played sync

### PR DESCRIPTION
**Pull request by sephrat**
This PR is a first step towards syncing played states from media servers to Ombi.
The long-term goal for this PR and future PRs is the following:

- Sync episodes and movies played status for every user, for every media server
- Show this information along with the requests to know if the user who made the request (and possibly other users) has watched it.

The current development progress for this PR is:

- [x] Cache Emby movie played state in Ombi
- [x] Enhance the requests API with "played" state
- [x] Display played state in the requests list
- [x] Allow to toggle this feature on/off (default: off), as this is highly experimental

Out of scope features for this PR (other PRs will follow):

- Episode sync
- Plex and Jellyfin sync

Some technical documentation:

- Refactored EmbyContentSync to reuse parts of code for EmbyPlayedSync
- Created a new table UserMoviePlayed in ExternalDb to cache played state

Let me know what you think of this and my plans!

### CODE REVIEW

**Comment by sephrat** [comment]
I'm ready for a review.

There is now a new column in the requests list:
image
A tooltip on the column header explains its meaning:
image
I also used a tooltip to show some additional information on the checkbox. 
image

The sync is done in the existing Emby sync jobs (full sync and recently added).

**Comment by sephrat** [comment]
Also I forgot to mention, I couldn't get the migrations to work with Mysql. I'm getting this error:
```
$ dotnet ef migrations add MovieUserPlayed --context Ombi.Store.Context.MySql.ExternalMySqlContext --startup-project ../Ombi
Build started...
Build succeeded.
Unable to create an object of type 'ExternalMySqlContext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728
```
Same command with Sqlite context worked fine, I can't figure out what I'm doing wrong. Hopefully it's just a button to press on your side to make this happen.

**Comment by tidusjar** [comment]
Regarding that error, you need to make your database.json file point to a MySQL database. It will then work

**Comment by sephrat** [comment]
Thanks, done!

**Pull request merged**
