### PR TITLE
feat: Adding postgres support to ombi (beta)

### PR DESCRIPTION
**Pull request by dben**
I saw the feature suggestion at https://features.ombi.io/suggestions/127609/add-postgresql-as-a-database-provider and thought It would be nice and quick to implement, as the *arrs all have postgres support but not mySql support built in.

This should be pretty straightforward - I added NpgSql and generated the migrations for it, then updated `DatabaseExtensions.cs`.

I've also built a docker image that includes this, based on the [LinuxServer Ombi container](https://github.com/linuxserver/docker-ombi) at `ghcr.io/dben/ombi:latest`. 

In my personal testing deploying the image in my nomad cluster, this appears to work identically to the mysql provider, at least for my setup (plex/radarr/sonarr/email notifications). Since it's just EF I woudn't expect too much divergence.

### CODE REVIEW

**Comment by dben** [comment]
After further testing, I made a few updates:

1. Fixed an issue where Npgsql was more strict than the app in timezone comparison, causing some failed inserts
2. Since Ombi has a few places where it uses raw SQL queries, I switched the postgres tables to be case-insensitive by converting identifiers to lowercase in the postgres migrations. This lets us avoid needing quotes for everything too.
3. I noticed a few unit tests were failng from midnght UTC to about 2-4 am UTC - I switched the `addHours` calls to `addMinutes` so there's only a down time of a few minutes instead.

**Comment by teambvd** [comment]
Just chiming in to note, I've been testing this for ~5 weeks now, all without issue. In an attempt to 'stress' the app, I added 4 multi-season TV series (~430 episodes combined) along with 8 movies, all in rapid succession; all went without a hitch, and was still more performant than adding a single series with the sqlite DB, at least to my eyes! 😮 

Great work @dben !

**Comment by dben** [comment]
Thanks for the testing - I've been running this PR as well on my personal instance since December, and haven't had any issues, although I've only had about a half dozen new movies and seven shortish tv shows added during that time.

**Comment by 0xFEEDC0DE64** [comment]
could you provide a working example for database.json, it will also be easier to update the docs later based on this

**Comment by 0xFEEDC0DE64** [comment]
the postgres implementation works like a charm, I guess it is ready for review and merging :)
image

**Comment by dben** [comment]
> could you provide a working example for database.json, it will also be easier to update the docs later based on this

sure, here's what I use (with the passwords redacted) - you can use separate databases too, but they all work lumped together:
```json
{
    "OmbiDatabase": {
        "Type": "Postgres",
        "ConnectionString": "Host=127.0.0.1;Port=5432;Database=ombi;Username=postgres;Password=password"
    },
    "SettingsDatabase": {
        "Type": "Postgres",
        "ConnectionString": "Host=127.0.0.1;Port=5432;Database=ombi;Username=postgres;Password=password"
    },
    "ExternalDatabase": {
        "Type": "Postgres",
        "ConnectionString": "Host=127.0.0.1;Port=5432;Database=ombi;Username=postgres;Password=password"
}
```

**Comment by tidusjar** [comment]
Considering people have been using this, i'll get this merged in soon

**Pull request merged**
