### PR TITLE
add crew on movie page

### PR DESCRIPTION
**Pull request by ketsapiwiq**
Add crew listing after cast listing, in order to show the director when available.

- The hyperlink is only on the photo, so when there's no photo, the person is not clickable. But this should probably be in another PR, I tried this: https://github.com/ketsapiwiq/Ombi/pull/1, but another solution is to implement a default photo as indicated in a TODO in the code
- If someone is confident enough to try to sort the Crew order so that the Director is at the beginning, I feel that would be very welcome.

Related:
- https://ombifeatures.featureupvote.com/suggestions/142857/search-by-directors
- https://ombifeatures.featureupvote.com/suggestions/320844/show-the-director-in-a-movie-page
- https://github.com/Ombi-app/Ombi/pull/1178

### CODE REVIEW

**Comment by tidusjar** [comment]
Looks good I’ll pull down to test soon

**Comment by screamjojo** [comment]
> Looks good I’ll pull down to test soon

Any news ?
Thanks again for your work :)

**Comment by tidusjar** [comment]
Didn’t get around to it and I’m currently on vacation. Will check when back

**Comment by tidusjar** [comment]
I fixed up a few little bits, including the ordering on director. Nice work :)

**Comment by ketsapiwiq** [comment]
Thanks!!

**Pull request merged**
