### PR TITLE
Update landingpage.component.html To Page Scrolling.

### PR DESCRIPTION
**Pull request by ExtremeFiretop**
Update landingpage.component.html To Page Scrolling on mobile devices.

This is to address issue:

https://github.com/Ombi-app/Ombi/issues/5046

Tested on my mobile with success.

### CODE REVIEW

**Review by tidusjar — CHANGES_REQUESTED** [review]
Thanks for the PR!

The only problem with this is that due to some other content div it seems there's always a scrollbar no matter the viewport size now. Looks like the `row` in the `small-middle-container` is causing it oddly enough

**Comment by ExtremeFiretop** [comment]
> Thanks for the PR!
> 
> The only problem with this is that due to some other content div it seems there's always a scrollbar no matter the viewport size now. Looks like the `row` in the `small-middle-container` is causing it oddly enough

I'm sorry if I over-stepped. I was just trying to learn a bit myself and troubleshoot at the same time.
I did mention this was only a workaround in the issue. So if this is not correct please feel free to close.

Otherwise, I can keep poking?

**Comment by tidusjar** [comment]
It's completely fine! Please feel free to keep poking away :)

**Comment by ExtremeFiretop** [comment]
> Thanks for the PR!
> 
> The only problem with this is that due to some other content div it seems there's always a scrollbar no matter the viewport size now. Looks like the `row` in the `small-middle-container` is causing it oddly enough

@tidusjar 

I believe I fixed it in commit: https://github.com/Ombi-app/Ombi/pull/5127/commits/18e0d90f49d3b3b64c8bea2a31daa7ce68c90fd4

Can you test/review and advise?

**Comment by ExtremeFiretop** [comment]
On my desktop with a ultrawide screen at 1440p, I have no scroll bar.
On my phone, I can scroll down to the button even with long text at the landing page.

(I am actually using HTML for the landing page, still no issues though)

**Comment by tidusjar** [comment]
Nice work!

**Review by tidusjar — APPROVED** [review]

**Pull request merged**
