### PR TITLE
Capitalizes V for tv show notification type. Refactors NotificationMessageCurlys class.

### LINKED ISSUE #4110: Capitalise 'v' in TV for notification type
**Describe the bug**
When Ombi sends a notification for a TV show using the {Type} variable, it does not have the V in TV capitalised.

**To Reproduce**
1. Setup notifications
2. Get notification
3. Check text

**Expected behavior**
It would be nice if the text was 'TV show' instead of 'Tv show'.

**Screenshots**
image

**Logs (Logs directory where Ombi is located)**
N/A

**Desktop (please complete the following information):**
 - OS: Debian 10

**Ombi Version (please complete the following information):**
 - Version: 4.0.1222.0
- Media Server: Emby
- Database Type: SQLite

**Additional context**
I use telegram notifications, but I would assume this is a global variable all types of notifications use.

### PR DESCRIPTION
**Pull request by bernarden**
Resolves #4110.
Cleans up duplication in NotificationMessageCurlys class.

### CODE REVIEW

**Comment by tidusjar** [comment]
Thanks for this! 

I'll take a look and test real soon!

**Comment by tidusjar** [comment]
Sorry! There are now conflicts due to this commit: https://github.com/Ombi-app/Ombi/commit/2dc364e96aeefe52d8a85d50e5f2b7927f810757

**Comment by bernarden** [comment]
I have also noticed that the poster url wasn't working for tv shows and addressed that in my original commit. My branch is now up to date with develop.😃

**Comment by tidusjar** [comment]
Ok, since this is quite time consuming to test manually, i'm going to write some unit tests around this area, and then ensure the tests pass with you code. Doing this now

**Comment by tidusjar** [comment]
Awesome! Unit tests are passing, will merge this in and commit the tests after! Thanks a lot! 

Certainly some nice improvements here!

**Pull request merged**
