### PR TITLE
An attempt at simplifying Sonarr sync

### PR DESCRIPTION
**Pull request by sephrat**
I say "attempt" because this has a few drawbacks that I'll try to explain.

**Current behaviour:**

1. Ombi would detect requests for a full season and would monitor the full season in Sonarr with a simple API call.
    1. It's quite simple and optimized because it avoids unecessary individual API calls
    2. This has some unwanted side effects:
       1. see #4588
        2. Monitoring a full season will result in future episodes being monitored, which is not what the request should allow. I'm talking about episodes that did not exist in tmdb/tvdb when processing the request, but would be added later on. Typical case is seasons spanning over 2 years like the last season of Vikings.
2. When requesting for a few episodes of a season, it would monitor the whole season and then unmonitor episodes that were not requested and not already monitored.
    -  This is quite a complex logic, although it works just fine.

**New behaviour developed in this PR:**

- Ombi will monitor individual episodes, regardless of a full season or not.
  - This makes 100% sure every episode in the request is monitored - no more, no less. 
  - It can generate a high number of API calls which could slow down the syncing process for large requests on low-end servers (not benchmarked, just a feeling).

**Tests**
Requesting for 3 full seasons of a show + a few episodes of a season:
image
image
It may seem off that the season is not flagged as monitored despite all episodes being monitored, but this actually makes sense from a Sonarr perspective and is expected behaviour. The episodes do show up in the "Missing" tab.

**Additional information**
I would recommend dropping support for V2 with this PR for the following reasons:
- This is a major change that I haven't tested on V2 at all
- Sonarr V2 has been EOL for more than a year now, time to upgrade!

Fixes https://github.com/Ombi-app/Ombi/issues/4588

### CODE REVIEW

**Comment by tidusjar** [comment]
I need to look at this more in-depth. But the problem with the season not being monitored is that if you do a search for that series, nothing will be found as sonarr skips unmonitored seasons

**Comment by sephrat** [comment]
Mmmh you're right. Quite curious since the search will work from the Missing tab. I'll think it through.

**Comment by sephrat** [comment]
>  the problem with the season not being monitored is that if you do a search for that series, nothing will be found as sonarr skips unmonitored seasons

Just to be sure we're talking about the same side-effects of having the season not monitored: 

1. Searching from the series' page in Sonarr with the global "Search monitored" button will indeed not trigger a search of the individually monitored episodes. This is a regression.
2. Searching from the series' page in Sonarr with the season search button or the episode search button works fine. So does manual searching from the Wanted > Missing tab in Sonarr.
3. Manual searching through the API that we use in Ombi works fine, be it either a season search or an episode search.
4. I'm still trying to figure out if auto-search in Sonarr works fine (when Sonarr automatically picks up newly released episodes through RSS sync). This not working would be a no-go for this PR in my opinion. I'll come back later with the result of my tests.

My personal opinion would be that side-effect n°1 is quite mitigated since in an automated setup, manual searches through Sonarr are an edge-case. In any case, it's a matter of pros and cons against the fact that monitoring the full season leads in future episodes being monitored despite not being part of the Ombi request. I'll let you be the judge of that. 😃

**Comment by tidusjar** [comment]
> monitoring the full season leads in future episodes being monitored despite not being part of the Ombi request.

I think that’s fine. 

I think that what you will find with the RSS feed is that if the series or season is not monitored it will not get picked up. I’ll ask the devs to confirm

**Comment by sephrat** [comment]
Thanks for looking into it. I'll come back with another approach.

**Comment by tidusjar** [comment]
Thank you for looking into it in the first place!

**Pull request closed without merging**
